"""Initial migration with hardening fields

Revision ID: 2c3e9dfd97d6
Revises: 
Create Date: 2026-01-29 00:44:24.883748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c3e9dfd97d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_sensor_links', sa.Column('calibration_formula', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('devices', sa.Column('is_battery_powered', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'is_battery_powered')
    op.drop_column('device_sensor_links', 'calibration_formula')
    # ### end Alembic commands ###
