
"""add_code_to_sensortype

Revision ID: 3f53d0928689
Revises: ebeeaa4ce7f3
Create Date: 2026-02-04 16:50:14.085669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3f53d0928689'
down_revision: Union[str, Sequence[str], None] = 'ebeeaa4ce7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_types', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_sensor_types_code'), 'sensor_types', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_types_code'), table_name='sensor_types')
    op.drop_column('sensor_types', 'code')
    # ### end Alembic commands ###
